---
# tasks file for enqack.maas-libvirt

- block: 

  - name: Remove existing user for kvm hosting
    user: 
      name: "{{ maas_libvirt_user_name }}"
      state: absent

  - name: Create user for kvm hosts
    user: 
      name: "{{ maas_libvirt_user_name }}"
      shell: /bin/sh
      append: true
      groups: "{{ maas_libvirt_user_groups }}"
      generate_ssh_key: true
      state: present

  - name: Get maas user pubic key on rack controller
    shell: cat ~maas/.ssh/id_rsa.pub
    register: ssh_key

  - name: Set authorized keys on kvm hosts
    authorized_key:
      user: "{{ maas_libvirt_user_name }}"
      state: present
      key: "{{ item[0] }}"
    delegate_to: "{{ item[1] }}"
    with_nested:
      - "{{ ssh_key.stdout }}"
      - "{{ groups[maas_libvirt_hosts_group_name] }}"

  when: inventory_hostname in groups[maas_libvirt_group_name]